# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=2)),
                ('acceptsrodents', models.BooleanField(default=False)),
                ('acceptsbirds', models.BooleanField()),
                ('acceptsdogscats', models.BooleanField()),
                ('acceptsprimates', models.BooleanField()),
                ('phone1', models.SmallIntegerField()),
                ('phone2', models.SmallIntegerField()),
                ('phone3', models.SmallIntegerField()),
            ],
        ),
    ]
