# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='acceptsbirds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='center',
            name='acceptsdogscats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='center',
            name='acceptsprimates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone1',
            field=models.SmallIntegerField(default=555),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone2',
            field=models.SmallIntegerField(default=555),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone3',
            field=models.SmallIntegerField(default=5555),
        ),
    ]
