# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0002_auto_20161104_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='State',
            new_name='state',
        ),
    ]
