# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0004_center_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='acceptsbirds',
        ),
        migrations.AddField(
            model_name='center',
            name='name',
            field=models.CharField(default='unnamed center', max_length=50),
        ),
        migrations.AddField(
            model_name='center',
            name='site',
            field=models.CharField(default='no website', max_length=30),
        ),
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.CharField(default='PA', max_length=2),
        ),
    ]
