# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0005_auto_20161104_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='siteurl',
            field=models.CharField(default='#', max_length=30),
        ),
    ]
