# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0009_auto_20161105_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(default='Unknown', max_length=12),
        ),
    ]
