# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLLapp', '0010_auto_20161105_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='siteurl',
            field=models.CharField(default='#', max_length=70),
        ),
    ]
